repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the specified version of isort
    hooks:
      - id: isort
        args:
          - --profile=black  # Set the import order style (change 'google' to your preferred style)          
  - repo: https://github.com/myint/autoflake
    rev: v2.3.0  # Use the latest version of autoflake
    hooks:
      - id: autoflake
        args:
          - --expand-star-imports
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --in-place
          - --exclude=__init__.py
          - --remove-duplicate-keys 
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.10
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0  # Use the latest MyPy version
    hooks:
      - id: mypy
        # Additional arguments to MyPy can be added here
        args: 
          # - --check-untyped-defs
          # - --strict-optional 
          - --ignore-missing-imports
          - --warn-redundant-casts   
          - --no-implicit-optional
        additional_dependencies: 
          - types-requests
          - types-PyYAML
          - types-Flask
          - types-Flask-Cors
          - types-pytz
          - flask_jsonpify
          - flask_restful
          - types-tabulate
          - types-psutil
          - types-ujson